//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Leaderboards')
export class LeaderboardsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  playerName: number;

  @Column('integer', { nullable: true })
  playerScore: number;

  @Column('integer', { nullable: true })
  rank: number;
}
