//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Matches')
export class MatchesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  matchID: string;

  @Column('integer', { nullable: true })
  participants: number;

  @Column('date', { nullable: true })
  matchStartTime: Date;

  @Column('date', { nullable: true })
  matchEndTime: Date;

  @Column('text', { nullable: true })
  matchResult: string;
}
