//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ChatTitle = () => {
  const record = useRecordContext();
  return <span>Chat {record ? `"${record.chatID}"` : ''}</span>;
};

export const ChatList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="chatID" />
      <ReferenceField source="senderUsername" reference="Players" />
      <ReferenceField source="receiverUsername" reference="Players" />
      <TextField source="message" />
      <DateField source="timestamp" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ChatEdit = () => (
  <Edit title={<ChatTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="chatID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="senderUsername" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverUsername" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="message" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="timestamp" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ChatCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="chatID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="senderUsername" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverUsername" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="message" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="timestamp" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="senderUsername"
    label="senderUsername"
    reference="Players"
    alwaysOn
  />,
  <ReferenceInput
    source="receiverUsername"
    label="receiverUsername"
    reference="Players"
    alwaysOn
  />,
  ,
  ,
];
