//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Players: {
      name: 'Players',
      fields: {
        score: 'Score',
        username: 'Username',
        email: 'Email',
        level: 'Level',
        id: 'id',
      },
    },
    Weapons: {
      name: 'Weapons',
      fields: {
        gunName: 'Gun Name',
        damage: 'Damage',
        range: 'Range',
        ammoCapacity: 'Ammo Capacity',
        costInCoins: 'Cost In Coins',
        id: 'id',
      },
    },
    Teams: {
      name: 'Teams',
      fields: {
        teamName: 'Team Name',
        members: 'Members',
        teamScore: 'Team Score',
        id: 'id',
      },
    },
    Matches: {
      name: 'Matches',
      fields: {
        matchID: 'Match Id',
        participants: 'Participants',
        matchStartTime: 'Match Start Time',
        matchEndTime: 'Match End Time',
        matchResult: 'Match Result',
        id: 'id',
      },
    },
    Leaderboards: {
      name: 'Leaderboards',
      fields: {
        playerName: 'Player Name',
        playerScore: 'Player Score',
        rank: 'Rank',
        id: 'id',
      },
    },
    Friends: {
      name: 'Friends',
      fields: {
        playerUsername: 'Player Username',
        friendUsername: 'Friend Username',
        status: 'Status',
        id: 'id',
      },
    },
    Chat: {
      name: 'Chat',
      fields: {
        chatID: 'Chat Id',
        senderUsername: 'Sender Username',
        receiverUsername: 'Receiver Username',
        message: 'Message',
        timestamp: 'Timestamp',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Players: {
      name: 'Players (fr)',
      fields: {
        score: 'Score (fr)',
        username: 'Username (fr)',
        email: 'Email (fr)',
        level: 'Level (fr)',
        id: 'id',
      },
    },
    Weapons: {
      name: 'Weapons (fr)',
      fields: {
        gunName: 'Gun Name (fr)',
        damage: 'Damage (fr)',
        range: 'Range (fr)',
        ammoCapacity: 'Ammo Capacity (fr)',
        costInCoins: 'Cost In Coins (fr)',
        id: 'id',
      },
    },
    Teams: {
      name: 'Teams (fr)',
      fields: {
        teamName: 'Team Name (fr)',
        members: 'Members (fr)',
        teamScore: 'Team Score (fr)',
        id: 'id',
      },
    },
    Matches: {
      name: 'Matches (fr)',
      fields: {
        matchID: 'Match Id (fr)',
        participants: 'Participants (fr)',
        matchStartTime: 'Match Start Time (fr)',
        matchEndTime: 'Match End Time (fr)',
        matchResult: 'Match Result (fr)',
        id: 'id',
      },
    },
    Leaderboards: {
      name: 'Leaderboards (fr)',
      fields: {
        playerName: 'Player Name (fr)',
        playerScore: 'Player Score (fr)',
        rank: 'Rank (fr)',
        id: 'id',
      },
    },
    Friends: {
      name: 'Friends (fr)',
      fields: {
        playerUsername: 'Player Username (fr)',
        friendUsername: 'Friend Username (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
    Chat: {
      name: 'Chat (fr)',
      fields: {
        chatID: 'Chat Id (fr)',
        senderUsername: 'Sender Username (fr)',
        receiverUsername: 'Receiver Username (fr)',
        message: 'Message (fr)',
        timestamp: 'Timestamp (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
